### ISSUE TITLE
PL Fourth volume. Peter-Branch-108

### ISSUE THREAD

**Issue by pmsprenger** [OpenGreekAndLatin/patrologia_latina-dev#108]

**Comment by pmsprenger** [comment]
Several remarks about Vol. 4:

    PL4_2_DE M.xml - Pages 991 until 1006 are missing. XML is not complete.
    PL4_3_CŒNA.xml - There is only one huge paragraph. There are numbers sprinkled around in the text that we could use for another level. Name for that level would be something "textchunk"-like?
    PL4_4_DE R.xml - I removed one textpart from this file. It was a random page some 20 pages later in the book. Strange how this has ended up here...? You can still find the text in the new file "Deleted_textparts(...).xml".

**Comment by annettegessner** [comment]
Questions:
PL4_2_DE M.xml - Is "just" the XML incomplete or does the problem occur in the PDF?PL4_3_CŒNA.xml - Did the text how it looked like in the PFD suggest some kind of structure? If not, I wouldn't try to give it one, since the text is not too long and the numbers in the text occurs so often, it wouldn't look like a text anymore, if we tried to separate each "textchunk" from each other. 
(In general: Theoretically, we can name textparts in whatever way we want, so we wouldn't have to call them "textchunks". But since it is good to have a general structure, I would suggest renaming the whole thing as chapter and the small parts as sections in a case like this, following our usual naming convention.)
PL4_4_DE R.xml - Did you look at the PDF? Sometimes pages get mixed up during the scanning process, this will occur again, I fear.

**Comment by annettegessner** [comment]
Peter wrote in the spreadsheet about PL4_5_CARM.xml:
"There also is a subtype="pref", but without n=""; so it shouldn't matter?"

Every textpart "matters" and should be addressable via CTS (i.e. have an n-element and fit the refsDecl)! 
So in cases like these please make the structure of the XML as easy as possible. In this case, it means, make the preface the same subtype as the other textparts on this level with the n-element set as "pr"!
So please @pmsprenger change the document accordingly: 
`<div subtype="pref" type="textpart"> and then 
<div n="1" subtype="section" type="textpart"> etc.`
to
`<div n="pr" subtype="section" type="textpart"> and then 
<div n="1" subtype="section" type="textpart"> etc.`
The same goes for addenda, appendices, etc.. 
(I also right now tried to document this in my workflow document.)

**Comment by annettegessner** [comment]
About PL4_2_DE M.xml --> see new issue #113

**Comment by pmsprenger** [comment]
About PL4_4_DE R.xml. Yes, so for some reason one paragraph from page 1053 got in there... I still can't imagine how this can happen.

Anyway, everything here should be done with the next merge. Closing this issue.
